### ISSUE TITLE
swf_tamperer error on detecting the format of Lossless image

### ISSUE THREAD

**Issue by tmtysk** [tmtysk/swf_ruby#3]
swf_tamperer raise error on detecting the format of lossless image when the format is 5 (NOT 3).

**Comment by oouchida** [comment]
tmtysk様
バグフィックスありがとうございます。
弊社でもダウンロードし確認させていただきました。
現在、正常に動作しております。

**Comment by tmtysk** [comment]
ご確認ありがとうございます！
